//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menees.RpnCalc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Menees.RpnCalc.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not fall within the expected range..
        /// </summary>
        internal static string Calculator_ArgumentException {
            get {
                return ResourceManager.GetString("Calculator_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string Calculator_ArgumentNullException {
            get {
                return ResourceManager.GetString("Calculator_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range of valid values..
        /// </summary>
        internal static string Calculator_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Calculator_ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow or underflow in the arithmetic operation..
        /// </summary>
        internal static string Calculator_ArithmeticException {
            get {
                return ResourceManager.GetString("Calculator_ArithmeticException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to divide by zero..
        /// </summary>
        internal static string Calculator_DivideByZeroException {
            get {
                return ResourceManager.GetString("Calculator_DivideByZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number encountered was not a finite value..
        /// </summary>
        internal static string Calculator_NotFiniteNumberException {
            get {
                return ResourceManager.GetString("Calculator_NotFiniteNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic operation resulted in an overflow..
        /// </summary>
        internal static string Calculator_OverflowException {
            get {
                return ResourceManager.GetString("Calculator_OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Calculator_PrefixedErrorFormat {
            get {
                return ResourceManager.GetString("Calculator_PrefixedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command..
        /// </summary>
        internal static string Calculator_UnknownCommand {
            get {
                return ResourceManager.GetString("Calculator_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} arguments are required..
        /// </summary>
        internal static string Commands_0ArgumentsAreRequired {
            get {
                return ResourceManager.GetString("Commands_0ArgumentsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument is required..
        /// </summary>
        internal static string Commands_AnArgumentIsRequired {
            get {
                return ResourceManager.GetString("Commands_AnArgumentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument count must be non-negative..
        /// </summary>
        internal static string Commands_CountMustBeNonNegative {
            get {
                return ResourceManager.GetString("Commands_CountMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} must be a scalar numeric value..
        /// </summary>
        internal static string Commands_Item0MustBeAScalarNumber {
            get {
                return ResourceManager.GetString("Commands_Item0MustBeAScalarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} must be a scalar or complex numeric value..
        /// </summary>
        internal static string Commands_Item0MustBeAScalarOrComplex {
            get {
                return ResourceManager.GetString("Commands_Item0MustBeAScalarOrComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} must be of type {1}..
        /// </summary>
        internal static string Commands_Item0MustHaveType1 {
            get {
                return ResourceManager.GetString("Commands_Item0MustHaveType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items {0} and {1} must be of the same type..
        /// </summary>
        internal static string Commands_Items0And1MustHaveTheSameType {
            get {
                return ResourceManager.GetString("Commands_Items0And1MustHaveTheSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string Commands_JoiningOr {
            get {
                return ResourceManager.GetString("Commands_JoiningOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position argument must be a positive integer..
        /// </summary>
        internal static string Commands_PositionMustBePositive {
            get {
                return ResourceManager.GetString("Commands_PositionMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two arguments are required..
        /// </summary>
        internal static string Commands_TwoArgumentsAreRequired {
            get {
                return ResourceManager.GetString("Commands_TwoArgumentsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A complex value with a non-zero imaginary part cannot be converted into a scalar value..
        /// </summary>
        internal static string ComplexValue_CannotCastToScalar {
            get {
                return ResourceManager.GetString("ComplexValue_CannotCastToScalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algebraic.
        /// </summary>
        internal static string DisplayFormat_Algebraic {
            get {
                return ResourceManager.GetString("DisplayFormat_Algebraic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        internal static string DisplayFormat_Binary {
            get {
                return ResourceManager.GetString("DisplayFormat_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string DisplayFormat_Common {
            get {
                return ResourceManager.GetString("DisplayFormat_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string DisplayFormat_Decimal {
            get {
                return ResourceManager.GetString("DisplayFormat_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string DisplayFormat_Fixed {
            get {
                return ResourceManager.GetString("DisplayFormat_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted.
        /// </summary>
        internal static string DisplayFormat_Formatted {
            get {
                return ResourceManager.GetString("DisplayFormat_Formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal.
        /// </summary>
        internal static string DisplayFormat_Hexadecimal {
            get {
                return ResourceManager.GetString("DisplayFormat_Hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Date/Time.
        /// </summary>
        internal static string DisplayFormat_LongDateTime {
            get {
                return ResourceManager.GetString("DisplayFormat_LongDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        internal static string DisplayFormat_Mixed {
            get {
                return ResourceManager.GetString("DisplayFormat_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string DisplayFormat_NameValueFormat {
            get {
                return ResourceManager.GetString("DisplayFormat_NameValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal.
        /// </summary>
        internal static string DisplayFormat_Octal {
            get {
                return ResourceManager.GetString("DisplayFormat_Octal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar.
        /// </summary>
        internal static string DisplayFormat_Polar {
            get {
                return ResourceManager.GetString("DisplayFormat_Polar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular.
        /// </summary>
        internal static string DisplayFormat_Rectangular {
            get {
                return ResourceManager.GetString("DisplayFormat_Rectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        internal static string DisplayFormat_Scientific {
            get {
                return ResourceManager.GetString("DisplayFormat_Scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Date/Time.
        /// </summary>
        internal static string DisplayFormat_ShortDateTime {
            get {
                return ResourceManager.GetString("DisplayFormat_ShortDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string DisplayFormat_Standard {
            get {
                return ResourceManager.GetString("DisplayFormat_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax..
        /// </summary>
        internal static string EntryLineParser_InvalidSyntax {
            get {
                return ResourceManager.GetString("EntryLineParser_InvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An integer value is required..
        /// </summary>
        internal static string MathCommands_IntegerIsRequired {
            get {
                return ResourceManager.GetString("MathCommands_IntegerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greatest Common Divisor.
        /// </summary>
        internal static string NumericValue_Gcd {
            get {
                return ResourceManager.GetString("NumericValue_Gcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string NumericValue_Invert {
            get {
                return ResourceManager.GetString("NumericValue_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus.
        /// </summary>
        internal static string NumericValue_Modulus {
            get {
                return ResourceManager.GetString("NumericValue_Modulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string NumericValue_Power {
            get {
                return ResourceManager.GetString("NumericValue_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change numeric value from {0} to {1}..
        /// </summary>
        internal static string NumericValue_UnableToChangeType {
            get {
                return ResourceManager.GetString("NumericValue_UnableToChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to compare all values in the specified range..
        /// </summary>
        internal static string StackCommands_UnableToCompare {
            get {
                return ResourceManager.GetString("StackCommands_UnableToCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Value.
        /// </summary>
        internal static string Value_Abs {
            get {
                return ResourceManager.GetString("Value_Abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Value_Add {
            get {
                return ResourceManager.GetString("Value_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported between arguments of type {1} and {2}..
        /// </summary>
        internal static string Value_BinaryOperationNotSupported {
            get {
                return ResourceManager.GetString("Value_BinaryOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        internal static string Value_Divide {
            get {
                return ResourceManager.GetString("Value_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        internal static string Value_Multiply {
            get {
                return ResourceManager.GetString("Value_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negate.
        /// </summary>
        internal static string Value_Negate {
            get {
                return ResourceManager.GetString("Value_Negate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        internal static string Value_Sign {
            get {
                return ResourceManager.GetString("Value_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        internal static string Value_Subtract {
            get {
                return ResourceManager.GetString("Value_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to compare {0} and {1}..
        /// </summary>
        internal static string Value_UnableToCompare {
            get {
                return ResourceManager.GetString("Value_UnableToCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not supported for an argument of type {1}..
        /// </summary>
        internal static string Value_UnaryOperationNotSupported {
            get {
                return ResourceManager.GetString("Value_UnaryOperationNotSupported", resourceCulture);
            }
        }
    }
}
